mutation <%= model_name_graphql_case %>Delete(
  $filters: <%= model_name %>FiltersSingle
) {
  <%= model_name_graphql_case %>Delete(
    filters: $filters
  ) {
    errors
    errorsFields {
      field
      message
    }
    node {
      __typename
      <%= for field <- graphql_fields do %><%= field %>
      <% end %>
    }
  }
}