query <%= model_name_graphql_case %>Single(
  $filters: <%= model_name %>FiltersSingle
) {
  <%= model_name_graphql_case %>Single(
    filters: $filters
  ) {
    __typename
    <%= for field <- graphql_fields do %><%= field %>
    <% end %>
  }
}